package com.antsim.creatures.ants;


// Паттерн "Фабрика" для создания муравьев
public class AntFactory {
    // Class below generated by llm!
    public static Ant createAnt(String type) {
        return switch (type.toLowerCase()) {
        case "worker" -> new WorkerAnt();
        case "queen" -> new QueenAnt();
        default -> throw new IllegalArgumentException("Неизвестный тип муравья");
        };
    }
}